[package]
name = "fmt-utils"
version = "0.1.0"
authors = ["sollyucko <solly.ucko@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fast_fmt = { version = "0.1.3", optional = true }